name: First Workflow

on: 
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    # https://github.com/actions/runner-images - GitHub-hosted runners

    steps:
      - name: Print greeting
        run: echo "Hello World"

      - name: Print goodbye
        run: echo "Done-bye"
